[versions]
agp = "8.12.3"
kotlin = "2.0.21"
#coreKtx = "1.18.0"
coreKtx = "1.13.1"
junit = "4.13.2"
#junitVersion = "1.3.0"
junitVersion = "1.1.5"
#espressoCore = "3.7.0"
espressoCore = "3.5.1"
appcompat = "1.7.1"
material = "1.13.0"
#activity = "1.12.4"
activity = "1.9.3"
constraintlayout = "2.2.1"
#compose
compose-bom = "2024.10.00"
#compose-compiler = "1.5.14"
#binding
#view-binding = "4.0.1"
view-binding = "8.7.0"
#coroutines
coroutines-android = "1.8.1"
coroutines-core = "1.8.1"
#hilt
#hilt = "2.48.1"
hilt = "2.51.1"
hilt-compose="1.2.0"
#room
#room = "2.6.1"
room = "2.7.0"
#retrofit
#retrofit = "2.9.0"
retrofit = "2.11.0"
#logging-interceptor = "4.11.0"
logging-interceptor = "4.12.0"
#kotlinx-serialization = "1.6.0"
kotlinx-serialization = "1.7.0"
retrofit-kotlinx-serialization-converter = "1.0.0"
#jetpack navigation
#navigation-graph = "2.7.7"
navigation-graph = "2.8.1"
#ksp
ksp = "2.0.21-1.0.28"
#gson
#code-gson = "2.10.1"
code-gson = "2.11.0"
#firebase
firebase-auth = "24.0.1"
services = "4.4.2"
material3 = "1.4.0"
# Lifecycle
lifecycle = "2.8.1"
# ViewModel
viewmodel = "2.8.1"
remoteCreationCore = "1.0.0-alpha07"
# zxing
zxing-android-embedded = "4.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#compose
androidx-compose-bom = {group = "androidx.compose", name="compose-bom", version.ref="compose-bom"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-graph" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

#binding
view-binding = { group = "com.android.databinding", name = "viewbinding", version.ref = "view-binding" }
#coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-android" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-core" }
#hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
#retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
retrofit-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization-converter" }
#jetpack navigation
navigation-graph-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-graph" }
navigation-graph-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-graph" }
#ksp
ksp-symbol-processing = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
#gson
gson = {group="com.google.code.gson", name="gson", version.ref="code-gson"}
# firebase
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebase-auth" }
# Lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodel" }
androidx-remote-creation-core = { group = "androidx.compose.remote", name = "remote-creation-core", version.ref = "remoteCreationCore" }
# zxing
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxing-android-embedded" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
pluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleServices = { id = "com.google.gms.google-services", version.ref = "services"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
